name: ferramentas
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  image: ^4.1.7
  share_plus: ^9.0.0
  google_mlkit_text_recognition: ^0.13.0
  uuid: ^4.3.3
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  intl: ^0.19.0
  table_calendar: ^3.1.1
  fl_chart: ^0.66.2
  percent_indicator: ^4.2.3
  http: ^1.1.0
  zxing2: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
